// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.example.entities;

/**
 * Protobuf type {@code com.proto.ClientServerMessageHeader}
 */
public  final class ClientServerMessageHeader extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.proto.ClientServerMessageHeader)
    ClientServerMessageHeaderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientServerMessageHeader.newBuilder() to construct.
  private ClientServerMessageHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientServerMessageHeader() {
    service_ = "";
    tokenId_ = "";
    compressed_ = "";
    platform_ = 0;
    ignoreMaintenance_ = false;
    hasVersion_ = false;
    hasShard_ = false;
    shard_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClientServerMessageHeader(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            service_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            tokenId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            compressed_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            platform_ = rawValue;
            break;
          }
          case 40: {

            ignoreMaintenance_ = input.readBool();
            break;
          }
          case 48: {

            hasVersion_ = input.readBool();
            break;
          }
          case 56: {

            hasShard_ = input.readBool();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            shard_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.entities.Model.internal_static_com_proto_ClientServerMessageHeader_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.entities.Model.internal_static_com_proto_ClientServerMessageHeader_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.entities.ClientServerMessageHeader.class, com.example.entities.ClientServerMessageHeader.Builder.class);
  }

  public static final int SERVICE_FIELD_NUMBER = 1;
  private volatile java.lang.Object service_;
  /**
   * <code>string service = 1;</code>
   */
  public java.lang.String getService() {
    java.lang.Object ref = service_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      service_ = s;
      return s;
    }
  }
  /**
   * <code>string service = 1;</code>
   */
  public com.google.protobuf.ByteString
      getServiceBytes() {
    java.lang.Object ref = service_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      service_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOKENID_FIELD_NUMBER = 2;
  private volatile java.lang.Object tokenId_;
  /**
   * <code>string tokenId = 2;</code>
   */
  public java.lang.String getTokenId() {
    java.lang.Object ref = tokenId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tokenId_ = s;
      return s;
    }
  }
  /**
   * <code>string tokenId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTokenIdBytes() {
    java.lang.Object ref = tokenId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tokenId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMPRESSED_FIELD_NUMBER = 3;
  private volatile java.lang.Object compressed_;
  /**
   * <code>string compressed = 3;</code>
   */
  public java.lang.String getCompressed() {
    java.lang.Object ref = compressed_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      compressed_ = s;
      return s;
    }
  }
  /**
   * <code>string compressed = 3;</code>
   */
  public com.google.protobuf.ByteString
      getCompressedBytes() {
    java.lang.Object ref = compressed_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      compressed_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLATFORM_FIELD_NUMBER = 4;
  private int platform_;
  /**
   * <code>.com.proto.Platform platform = 4;</code>
   */
  public int getPlatformValue() {
    return platform_;
  }
  /**
   * <code>.com.proto.Platform platform = 4;</code>
   */
  public com.example.entities.Platform getPlatform() {
    @SuppressWarnings("deprecation")
    com.example.entities.Platform result = com.example.entities.Platform.valueOf(platform_);
    return result == null ? com.example.entities.Platform.UNRECOGNIZED : result;
  }

  public static final int IGNOREMAINTENANCE_FIELD_NUMBER = 5;
  private boolean ignoreMaintenance_;
  /**
   * <pre>
   * 是否不管停机维护
   * </pre>
   *
   * <code>bool ignoreMaintenance = 5;</code>
   */
  public boolean getIgnoreMaintenance() {
    return ignoreMaintenance_;
  }

  public static final int HASVERSION_FIELD_NUMBER = 6;
  private boolean hasVersion_;
  /**
   * <code>bool hasVersion = 6;</code>
   */
  public boolean getHasVersion() {
    return hasVersion_;
  }

  public static final int HASSHARD_FIELD_NUMBER = 7;
  private boolean hasShard_;
  /**
   * <code>bool hasShard = 7;</code>
   */
  public boolean getHasShard() {
    return hasShard_;
  }

  public static final int SHARD_FIELD_NUMBER = 8;
  private volatile java.lang.Object shard_;
  /**
   * <code>string shard = 8;</code>
   */
  public java.lang.String getShard() {
    java.lang.Object ref = shard_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      shard_ = s;
      return s;
    }
  }
  /**
   * <code>string shard = 8;</code>
   */
  public com.google.protobuf.ByteString
      getShardBytes() {
    java.lang.Object ref = shard_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      shard_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getServiceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, service_);
    }
    if (!getTokenIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tokenId_);
    }
    if (!getCompressedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, compressed_);
    }
    if (platform_ != com.example.entities.Platform.ANDROID.getNumber()) {
      output.writeEnum(4, platform_);
    }
    if (ignoreMaintenance_ != false) {
      output.writeBool(5, ignoreMaintenance_);
    }
    if (hasVersion_ != false) {
      output.writeBool(6, hasVersion_);
    }
    if (hasShard_ != false) {
      output.writeBool(7, hasShard_);
    }
    if (!getShardBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, shard_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getServiceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, service_);
    }
    if (!getTokenIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tokenId_);
    }
    if (!getCompressedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, compressed_);
    }
    if (platform_ != com.example.entities.Platform.ANDROID.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, platform_);
    }
    if (ignoreMaintenance_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, ignoreMaintenance_);
    }
    if (hasVersion_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, hasVersion_);
    }
    if (hasShard_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, hasShard_);
    }
    if (!getShardBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, shard_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.entities.ClientServerMessageHeader)) {
      return super.equals(obj);
    }
    com.example.entities.ClientServerMessageHeader other = (com.example.entities.ClientServerMessageHeader) obj;

    boolean result = true;
    result = result && getService()
        .equals(other.getService());
    result = result && getTokenId()
        .equals(other.getTokenId());
    result = result && getCompressed()
        .equals(other.getCompressed());
    result = result && platform_ == other.platform_;
    result = result && (getIgnoreMaintenance()
        == other.getIgnoreMaintenance());
    result = result && (getHasVersion()
        == other.getHasVersion());
    result = result && (getHasShard()
        == other.getHasShard());
    result = result && getShard()
        .equals(other.getShard());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERVICE_FIELD_NUMBER;
    hash = (53 * hash) + getService().hashCode();
    hash = (37 * hash) + TOKENID_FIELD_NUMBER;
    hash = (53 * hash) + getTokenId().hashCode();
    hash = (37 * hash) + COMPRESSED_FIELD_NUMBER;
    hash = (53 * hash) + getCompressed().hashCode();
    hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
    hash = (53 * hash) + platform_;
    hash = (37 * hash) + IGNOREMAINTENANCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIgnoreMaintenance());
    hash = (37 * hash) + HASVERSION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasVersion());
    hash = (37 * hash) + HASSHARD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasShard());
    hash = (37 * hash) + SHARD_FIELD_NUMBER;
    hash = (53 * hash) + getShard().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.entities.ClientServerMessageHeader parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.entities.ClientServerMessageHeader parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.entities.ClientServerMessageHeader parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.entities.ClientServerMessageHeader parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.entities.ClientServerMessageHeader parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.entities.ClientServerMessageHeader parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.entities.ClientServerMessageHeader parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.entities.ClientServerMessageHeader parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.entities.ClientServerMessageHeader parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.entities.ClientServerMessageHeader parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.entities.ClientServerMessageHeader parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.entities.ClientServerMessageHeader parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.entities.ClientServerMessageHeader prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.proto.ClientServerMessageHeader}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.proto.ClientServerMessageHeader)
      com.example.entities.ClientServerMessageHeaderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.entities.Model.internal_static_com_proto_ClientServerMessageHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.entities.Model.internal_static_com_proto_ClientServerMessageHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.entities.ClientServerMessageHeader.class, com.example.entities.ClientServerMessageHeader.Builder.class);
    }

    // Construct using com.example.entities.ClientServerMessageHeader.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      service_ = "";

      tokenId_ = "";

      compressed_ = "";

      platform_ = 0;

      ignoreMaintenance_ = false;

      hasVersion_ = false;

      hasShard_ = false;

      shard_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.entities.Model.internal_static_com_proto_ClientServerMessageHeader_descriptor;
    }

    @java.lang.Override
    public com.example.entities.ClientServerMessageHeader getDefaultInstanceForType() {
      return com.example.entities.ClientServerMessageHeader.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.entities.ClientServerMessageHeader build() {
      com.example.entities.ClientServerMessageHeader result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.entities.ClientServerMessageHeader buildPartial() {
      com.example.entities.ClientServerMessageHeader result = new com.example.entities.ClientServerMessageHeader(this);
      result.service_ = service_;
      result.tokenId_ = tokenId_;
      result.compressed_ = compressed_;
      result.platform_ = platform_;
      result.ignoreMaintenance_ = ignoreMaintenance_;
      result.hasVersion_ = hasVersion_;
      result.hasShard_ = hasShard_;
      result.shard_ = shard_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.entities.ClientServerMessageHeader) {
        return mergeFrom((com.example.entities.ClientServerMessageHeader)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.entities.ClientServerMessageHeader other) {
      if (other == com.example.entities.ClientServerMessageHeader.getDefaultInstance()) return this;
      if (!other.getService().isEmpty()) {
        service_ = other.service_;
        onChanged();
      }
      if (!other.getTokenId().isEmpty()) {
        tokenId_ = other.tokenId_;
        onChanged();
      }
      if (!other.getCompressed().isEmpty()) {
        compressed_ = other.compressed_;
        onChanged();
      }
      if (other.platform_ != 0) {
        setPlatformValue(other.getPlatformValue());
      }
      if (other.getIgnoreMaintenance() != false) {
        setIgnoreMaintenance(other.getIgnoreMaintenance());
      }
      if (other.getHasVersion() != false) {
        setHasVersion(other.getHasVersion());
      }
      if (other.getHasShard() != false) {
        setHasShard(other.getHasShard());
      }
      if (!other.getShard().isEmpty()) {
        shard_ = other.shard_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.entities.ClientServerMessageHeader parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.entities.ClientServerMessageHeader) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object service_ = "";
    /**
     * <code>string service = 1;</code>
     */
    public java.lang.String getService() {
      java.lang.Object ref = service_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        service_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string service = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServiceBytes() {
      java.lang.Object ref = service_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        service_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string service = 1;</code>
     */
    public Builder setService(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      service_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string service = 1;</code>
     */
    public Builder clearService() {
      
      service_ = getDefaultInstance().getService();
      onChanged();
      return this;
    }
    /**
     * <code>string service = 1;</code>
     */
    public Builder setServiceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      service_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object tokenId_ = "";
    /**
     * <code>string tokenId = 2;</code>
     */
    public java.lang.String getTokenId() {
      java.lang.Object ref = tokenId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tokenId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tokenId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenIdBytes() {
      java.lang.Object ref = tokenId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tokenId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tokenId = 2;</code>
     */
    public Builder setTokenId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tokenId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tokenId = 2;</code>
     */
    public Builder clearTokenId() {
      
      tokenId_ = getDefaultInstance().getTokenId();
      onChanged();
      return this;
    }
    /**
     * <code>string tokenId = 2;</code>
     */
    public Builder setTokenIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tokenId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object compressed_ = "";
    /**
     * <code>string compressed = 3;</code>
     */
    public java.lang.String getCompressed() {
      java.lang.Object ref = compressed_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        compressed_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string compressed = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCompressedBytes() {
      java.lang.Object ref = compressed_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        compressed_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string compressed = 3;</code>
     */
    public Builder setCompressed(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      compressed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string compressed = 3;</code>
     */
    public Builder clearCompressed() {
      
      compressed_ = getDefaultInstance().getCompressed();
      onChanged();
      return this;
    }
    /**
     * <code>string compressed = 3;</code>
     */
    public Builder setCompressedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      compressed_ = value;
      onChanged();
      return this;
    }

    private int platform_ = 0;
    /**
     * <code>.com.proto.Platform platform = 4;</code>
     */
    public int getPlatformValue() {
      return platform_;
    }
    /**
     * <code>.com.proto.Platform platform = 4;</code>
     */
    public Builder setPlatformValue(int value) {
      platform_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.proto.Platform platform = 4;</code>
     */
    public com.example.entities.Platform getPlatform() {
      @SuppressWarnings("deprecation")
      com.example.entities.Platform result = com.example.entities.Platform.valueOf(platform_);
      return result == null ? com.example.entities.Platform.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.proto.Platform platform = 4;</code>
     */
    public Builder setPlatform(com.example.entities.Platform value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      platform_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.proto.Platform platform = 4;</code>
     */
    public Builder clearPlatform() {
      
      platform_ = 0;
      onChanged();
      return this;
    }

    private boolean ignoreMaintenance_ ;
    /**
     * <pre>
     * 是否不管停机维护
     * </pre>
     *
     * <code>bool ignoreMaintenance = 5;</code>
     */
    public boolean getIgnoreMaintenance() {
      return ignoreMaintenance_;
    }
    /**
     * <pre>
     * 是否不管停机维护
     * </pre>
     *
     * <code>bool ignoreMaintenance = 5;</code>
     */
    public Builder setIgnoreMaintenance(boolean value) {
      
      ignoreMaintenance_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否不管停机维护
     * </pre>
     *
     * <code>bool ignoreMaintenance = 5;</code>
     */
    public Builder clearIgnoreMaintenance() {
      
      ignoreMaintenance_ = false;
      onChanged();
      return this;
    }

    private boolean hasVersion_ ;
    /**
     * <code>bool hasVersion = 6;</code>
     */
    public boolean getHasVersion() {
      return hasVersion_;
    }
    /**
     * <code>bool hasVersion = 6;</code>
     */
    public Builder setHasVersion(boolean value) {
      
      hasVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool hasVersion = 6;</code>
     */
    public Builder clearHasVersion() {
      
      hasVersion_ = false;
      onChanged();
      return this;
    }

    private boolean hasShard_ ;
    /**
     * <code>bool hasShard = 7;</code>
     */
    public boolean getHasShard() {
      return hasShard_;
    }
    /**
     * <code>bool hasShard = 7;</code>
     */
    public Builder setHasShard(boolean value) {
      
      hasShard_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool hasShard = 7;</code>
     */
    public Builder clearHasShard() {
      
      hasShard_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object shard_ = "";
    /**
     * <code>string shard = 8;</code>
     */
    public java.lang.String getShard() {
      java.lang.Object ref = shard_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shard_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string shard = 8;</code>
     */
    public com.google.protobuf.ByteString
        getShardBytes() {
      java.lang.Object ref = shard_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shard_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string shard = 8;</code>
     */
    public Builder setShard(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      shard_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string shard = 8;</code>
     */
    public Builder clearShard() {
      
      shard_ = getDefaultInstance().getShard();
      onChanged();
      return this;
    }
    /**
     * <code>string shard = 8;</code>
     */
    public Builder setShardBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      shard_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.proto.ClientServerMessageHeader)
  }

  // @@protoc_insertion_point(class_scope:com.proto.ClientServerMessageHeader)
  private static final com.example.entities.ClientServerMessageHeader DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.entities.ClientServerMessageHeader();
  }

  public static com.example.entities.ClientServerMessageHeader getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientServerMessageHeader>
      PARSER = new com.google.protobuf.AbstractParser<ClientServerMessageHeader>() {
    @java.lang.Override
    public ClientServerMessageHeader parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClientServerMessageHeader(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientServerMessageHeader> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientServerMessageHeader> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.entities.ClientServerMessageHeader getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

