// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.example.entities;

/**
 * Protobuf enum {@code com.proto.GatewayStatus}
 */
public enum GatewayStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>GW_OK = 0;</code>
   */
  GW_OK(0),
  /**
   * <code>GW_UNDER_MAINTENANCE = 1;</code>
   */
  GW_UNDER_MAINTENANCE(1),
  /**
   * <code>GW_WAIT_AND_RETRY = 2;</code>
   */
  GW_WAIT_AND_RETRY(2),
  /**
   * <code>GW_ERROR = 3;</code>
   */
  GW_ERROR(3),
  /**
   * <code>GW_REDIRECT = 4;</code>
   */
  GW_REDIRECT(4),
  /**
   * <code>GW_NO_RESPONSE = 5;</code>
   */
  GW_NO_RESPONSE(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>GW_OK = 0;</code>
   */
  public static final int GW_OK_VALUE = 0;
  /**
   * <code>GW_UNDER_MAINTENANCE = 1;</code>
   */
  public static final int GW_UNDER_MAINTENANCE_VALUE = 1;
  /**
   * <code>GW_WAIT_AND_RETRY = 2;</code>
   */
  public static final int GW_WAIT_AND_RETRY_VALUE = 2;
  /**
   * <code>GW_ERROR = 3;</code>
   */
  public static final int GW_ERROR_VALUE = 3;
  /**
   * <code>GW_REDIRECT = 4;</code>
   */
  public static final int GW_REDIRECT_VALUE = 4;
  /**
   * <code>GW_NO_RESPONSE = 5;</code>
   */
  public static final int GW_NO_RESPONSE_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static GatewayStatus valueOf(int value) {
    return forNumber(value);
  }

  public static GatewayStatus forNumber(int value) {
    switch (value) {
      case 0: return GW_OK;
      case 1: return GW_UNDER_MAINTENANCE;
      case 2: return GW_WAIT_AND_RETRY;
      case 3: return GW_ERROR;
      case 4: return GW_REDIRECT;
      case 5: return GW_NO_RESPONSE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<GatewayStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      GatewayStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<GatewayStatus>() {
          public GatewayStatus findValueByNumber(int number) {
            return GatewayStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.example.entities.Model.getDescriptor().getEnumTypes().get(0);
  }

  private static final GatewayStatus[] VALUES = values();

  public static GatewayStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private GatewayStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.proto.GatewayStatus)
}

