// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.example.entities;

public final class Model {
  private Model() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_proto_ClientServerMessageHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_proto_ClientServerMessageHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_proto_ServerClientMessageHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_proto_ServerClientMessageHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013model.proto\022\tcom.proto\"\310\001\n\031ClientServe" +
      "rMessageHeader\022\017\n\007service\030\001 \001(\t\022\017\n\007token" +
      "Id\030\002 \001(\t\022\022\n\ncompressed\030\003 \001(\t\022%\n\010platform" +
      "\030\004 \001(\0162\023.com.proto.Platform\022\031\n\021ignoreMai" +
      "ntenance\030\005 \001(\010\022\022\n\nhasVersion\030\006 \001(\010\022\020\n\010ha" +
      "sShard\030\007 \001(\010\022\r\n\005shard\030\010 \001(\t\"\242\001\n\031ServerCl" +
      "ientMessageHeader\022\017\n\007version\030\001 \001(\t\022\021\n\tti" +
      "mestamp\030\002 \001(\003\022\017\n\007tokenId\030\003 \001(\t\022\022\n\nnewVer" +
      "sion\030\004 \001(\t\022\022\n\ncompressed\030\005 \001(\010\022(\n\006status" +
      "\030\006 \001(\0162\030.com.proto.GatewayStatus*~\n\rGate" +
      "wayStatus\022\t\n\005GW_OK\020\000\022\030\n\024GW_UNDER_MAINTEN" +
      "ANCE\020\001\022\025\n\021GW_WAIT_AND_RETRY\020\002\022\014\n\010GW_ERRO" +
      "R\020\003\022\017\n\013GW_REDIRECT\020\004\022\022\n\016GW_NO_RESPONSE\020\005" +
      "* \n\010Platform\022\013\n\007ANDROID\020\000\022\007\n\003IOS\020\001B\030\n\024co" +
      "m.example.entitiesP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_proto_ClientServerMessageHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_proto_ClientServerMessageHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_proto_ClientServerMessageHeader_descriptor,
        new java.lang.String[] { "Service", "TokenId", "Compressed", "Platform", "IgnoreMaintenance", "HasVersion", "HasShard", "Shard", });
    internal_static_com_proto_ServerClientMessageHeader_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_proto_ServerClientMessageHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_proto_ServerClientMessageHeader_descriptor,
        new java.lang.String[] { "Version", "Timestamp", "TokenId", "NewVersion", "Compressed", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
