// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.example.entities;

/**
 * Protobuf enum {@code com.proto.Platform}
 */
public enum Platform
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ANDROID = 0;</code>
   */
  ANDROID(0),
  /**
   * <code>IOS = 1;</code>
   */
  IOS(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ANDROID = 0;</code>
   */
  public static final int ANDROID_VALUE = 0;
  /**
   * <code>IOS = 1;</code>
   */
  public static final int IOS_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Platform valueOf(int value) {
    return forNumber(value);
  }

  public static Platform forNumber(int value) {
    switch (value) {
      case 0: return ANDROID;
      case 1: return IOS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Platform>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Platform> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Platform>() {
          public Platform findValueByNumber(int number) {
            return Platform.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.example.entities.Model.getDescriptor().getEnumTypes().get(1);
  }

  private static final Platform[] VALUES = values();

  public static Platform valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Platform(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.proto.Platform)
}

