// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.example.entities;

public interface ServerClientMessageHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.proto.ServerClientMessageHeader)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string version = 1;</code>
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 1;</code>
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>int64 timestamp = 2;</code>
   */
  long getTimestamp();

  /**
   * <code>string tokenId = 3;</code>
   */
  java.lang.String getTokenId();
  /**
   * <code>string tokenId = 3;</code>
   */
  com.google.protobuf.ByteString
      getTokenIdBytes();

  /**
   * <code>string newVersion = 4;</code>
   */
  java.lang.String getNewVersion();
  /**
   * <code>string newVersion = 4;</code>
   */
  com.google.protobuf.ByteString
      getNewVersionBytes();

  /**
   * <code>bool compressed = 5;</code>
   */
  boolean getCompressed();

  /**
   * <code>.com.proto.GatewayStatus status = 6;</code>
   */
  int getStatusValue();
  /**
   * <code>.com.proto.GatewayStatus status = 6;</code>
   */
  com.example.entities.GatewayStatus getStatus();
}
