// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package com.example.req;

public interface TestParamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.proto.TestParam)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>int32 id = 2;</code>
   */
  int getId();
}
